// source: engine_service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.engine_api.CreateEnclaveArgs', null, global);
goog.exportSymbol('proto.engine_api.CreateEnclaveResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.engine_api.CreateEnclaveArgs = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.engine_api.CreateEnclaveArgs, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.engine_api.CreateEnclaveArgs.displayName = 'proto.engine_api.CreateEnclaveArgs';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.engine_api.CreateEnclaveResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.engine_api.CreateEnclaveResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.engine_api.CreateEnclaveResponse.displayName = 'proto.engine_api.CreateEnclaveResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.engine_api.CreateEnclaveArgs.prototype.toObject = function(opt_includeInstance) {
  return proto.engine_api.CreateEnclaveArgs.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.engine_api.CreateEnclaveArgs} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.engine_api.CreateEnclaveArgs.toObject = function(includeInstance, msg) {
  var f, obj = {
    enclaveId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    apiContainerImage: jspb.Message.getFieldWithDefault(msg, 2, ""),
    isPartitioningEnabled: jspb.Message.getBooleanFieldWithDefault(msg, 3, false),
    shouldPublishAllPorts: jspb.Message.getBooleanFieldWithDefault(msg, 4, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.engine_api.CreateEnclaveArgs}
 */
proto.engine_api.CreateEnclaveArgs.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.engine_api.CreateEnclaveArgs;
  return proto.engine_api.CreateEnclaveArgs.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.engine_api.CreateEnclaveArgs} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.engine_api.CreateEnclaveArgs}
 */
proto.engine_api.CreateEnclaveArgs.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setEnclaveId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setApiContainerImage(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsPartitioningEnabled(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setShouldPublishAllPorts(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.engine_api.CreateEnclaveArgs.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.engine_api.CreateEnclaveArgs.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.engine_api.CreateEnclaveArgs} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.engine_api.CreateEnclaveArgs.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEnclaveId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getApiContainerImage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getIsPartitioningEnabled();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getShouldPublishAllPorts();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
};


/**
 * optional string enclave_id = 1;
 * @return {string}
 */
proto.engine_api.CreateEnclaveArgs.prototype.getEnclaveId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.engine_api.CreateEnclaveArgs} returns this
 */
proto.engine_api.CreateEnclaveArgs.prototype.setEnclaveId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string api_container_image = 2;
 * @return {string}
 */
proto.engine_api.CreateEnclaveArgs.prototype.getApiContainerImage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.engine_api.CreateEnclaveArgs} returns this
 */
proto.engine_api.CreateEnclaveArgs.prototype.setApiContainerImage = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional bool is_partitioning_enabled = 3;
 * @return {boolean}
 */
proto.engine_api.CreateEnclaveArgs.prototype.getIsPartitioningEnabled = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.engine_api.CreateEnclaveArgs} returns this
 */
proto.engine_api.CreateEnclaveArgs.prototype.setIsPartitioningEnabled = function(value) {
  return jspb.Message.setProto3BooleanField(this, 3, value);
};


/**
 * optional bool should_publish_all_ports = 4;
 * @return {boolean}
 */
proto.engine_api.CreateEnclaveArgs.prototype.getShouldPublishAllPorts = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.engine_api.CreateEnclaveArgs} returns this
 */
proto.engine_api.CreateEnclaveArgs.prototype.setShouldPublishAllPorts = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.engine_api.CreateEnclaveResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.engine_api.CreateEnclaveResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.engine_api.CreateEnclaveResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.engine_api.CreateEnclaveResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    networkId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    networkIp: jspb.Message.getFieldWithDefault(msg, 2, ""),
    apiContainerId: jspb.Message.getFieldWithDefault(msg, 3, ""),
    apiContainerIp: jspb.Message.getFieldWithDefault(msg, 4, ""),
    apiContainerHostIp: jspb.Message.getFieldWithDefault(msg, 5, ""),
    apiContainerHostPort: jspb.Message.getFieldWithDefault(msg, 6, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.engine_api.CreateEnclaveResponse}
 */
proto.engine_api.CreateEnclaveResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.engine_api.CreateEnclaveResponse;
  return proto.engine_api.CreateEnclaveResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.engine_api.CreateEnclaveResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.engine_api.CreateEnclaveResponse}
 */
proto.engine_api.CreateEnclaveResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setNetworkId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setNetworkIp(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setApiContainerId(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setApiContainerIp(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setApiContainerHostIp(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setApiContainerHostPort(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.engine_api.CreateEnclaveResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.engine_api.CreateEnclaveResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.engine_api.CreateEnclaveResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.engine_api.CreateEnclaveResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNetworkId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getNetworkIp();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getApiContainerId();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getApiContainerIp();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getApiContainerHostIp();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getApiContainerHostPort();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * optional string network_id = 1;
 * @return {string}
 */
proto.engine_api.CreateEnclaveResponse.prototype.getNetworkId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.engine_api.CreateEnclaveResponse} returns this
 */
proto.engine_api.CreateEnclaveResponse.prototype.setNetworkId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string network_ip = 2;
 * @return {string}
 */
proto.engine_api.CreateEnclaveResponse.prototype.getNetworkIp = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.engine_api.CreateEnclaveResponse} returns this
 */
proto.engine_api.CreateEnclaveResponse.prototype.setNetworkIp = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string api_container_id = 3;
 * @return {string}
 */
proto.engine_api.CreateEnclaveResponse.prototype.getApiContainerId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.engine_api.CreateEnclaveResponse} returns this
 */
proto.engine_api.CreateEnclaveResponse.prototype.setApiContainerId = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string api_container_ip = 4;
 * @return {string}
 */
proto.engine_api.CreateEnclaveResponse.prototype.getApiContainerIp = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.engine_api.CreateEnclaveResponse} returns this
 */
proto.engine_api.CreateEnclaveResponse.prototype.setApiContainerIp = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string api_container_host_ip = 5;
 * @return {string}
 */
proto.engine_api.CreateEnclaveResponse.prototype.getApiContainerHostIp = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.engine_api.CreateEnclaveResponse} returns this
 */
proto.engine_api.CreateEnclaveResponse.prototype.setApiContainerHostIp = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string api_container_host_port = 6;
 * @return {string}
 */
proto.engine_api.CreateEnclaveResponse.prototype.getApiContainerHostPort = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.engine_api.CreateEnclaveResponse} returns this
 */
proto.engine_api.CreateEnclaveResponse.prototype.setApiContainerHostPort = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


goog.object.extend(exports, proto.engine_api);
